### ISSUE TITLE
Support for GNU-Taler?

### ISSUE THREAD

**Issue by poVoq** [dentm42/dm42-hubzilla-addons#1]
Seems like the perfect project to be on the forefront of this cool new payment system:
https://taler.net/

It's still in an experimental phase, but should be more or less ready for use this year it seems. The demos work quite nicely already.

What is GNU-Taler? Not another cryptocurrency :) Think of it more like an open-source sort of federalized paypal.

**Comment by dentm42** [comment]
Interesting!  The architecture is pluggable and will support any sort of payment system someone wants to write  plugin for.  This project is more or less a "data broker" - keeping track of the absolute basics of where an order and it's associated items are in the system.  It is built to allow plugins to create different types of items, to handle different types of payment systems, and to even have different fulfillment processes.

I'm sure if Taler gains steam, someone will have interest to create a plugin for it!
